language: go

go:
  - "1.10"

matrix:
  - fast_finish: true

install:
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - mkdir -p $GOPATH/bin
  - wget https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -O $GOPATH/bin/dep && chmod +x $GOPATH/bin/dep

script:
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - make

after_success:
  - bash tools/codecov
